POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "another blog",
  "author": "another author",
  "url": "esimerkki.fi",
  "likes": 10,
  "userId": "688f97f20583c80a311bbb3e"
}